
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Pertemuan6 extends javax.swing.JFrame {

    /**
     * Creates new form Pertemuan6
     */
    
    String daftarBelanja="";
    int totalBayarAkhir=0;
    DefaultListModel<String>modelDaftarPesanan = new DefaultListModel<>();
    int grandTotal = 0;
    
    public Pertemuan6() {
        initComponents();
        
        this.getContentPane().setBackground(Color.WHITE);
        
        dropdown_kategori.removeAllItems();
        dropdown_kategori.addItem("Makanan");
        dropdown_kategori.addItem("Minuman");
        dropdown_kategori.addItem("Snack");
        
        pembayaran_box.removeAllItems();
        pembayaran_box.addItem("Tunai");
        pembayaran_box.addItem("QRIS");
        pembayaran_box.addItem("Transfer Bank / Debit");
    }

    private void hitungTotal() {
        try {
        // Hanya menghitung jika textfield harga tidak kosong
            if (!harga.getText().isEmpty()) {
                int hrg = Integer.parseInt(harga.getText());
                int jml = (Integer) jumlah.getValue(); // Mengambil nilai dari JSpinner 'jumlah'
            
            // Mencegah user memasukkan angka minus atau nol di JSpinner
            if (jml < 1) {
                jumlah.setValue(1);
                jml = 1;
                }
            
                int total = hrg * jml;
                total_harga.setText(String.valueOf(total)); // Menampilkan ke textfield 'total_harga'
            }
        } catch (NumberFormatException e) {
            total_harga.setText("0");
        }
        
        list_keranjang.setModel(modelDaftarPesanan);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        no_meja_field = new javax.swing.JTextField();
        nama_field = new javax.swing.JTextField();
        dropdown_kategori = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_menu = new javax.swing.JList<>();
        pesan_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jumlah = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        total_harga = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        catatan_field = new javax.swing.JTextField();
        pembayaran_box = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_hapus_item = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_keranjang = new javax.swing.JList<>();
        cetakStruck = new javax.swing.JButton();
        label_grand_total = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("KEYAN'S VITE CUISINE ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("No. Meja :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pemesan :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Kategori:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Menu : ");

        no_meja_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_meja_fieldActionPerformed(evt);
            }
        });

        nama_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_fieldActionPerformed(evt);
            }
        });

        dropdown_kategori.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        dropdown_kategori.setForeground(new java.awt.Color(0, 51, 102));
        dropdown_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        dropdown_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kategoriActionPerformed(evt);
            }
        });

        list_menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        list_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_menu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_menuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_menu);

        pesan_button.setBackground(new java.awt.Color(0, 51, 102));
        pesan_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pesan_button.setForeground(new java.awt.Color(255, 255, 255));
        pesan_button.setText("Tambah Keranjang");
        pesan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan_buttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Harga Satuan : ");

        harga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Jumlah Porsi :");

        jumlah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jumlahStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Total Harga :");

        total_harga.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        total_harga.setForeground(new java.awt.Color(0, 51, 102));

        reset.setBackground(new java.awt.Color(255, 204, 204));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 0, 0));
        reset.setText("Batal");
        reset.setBorderPainted(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Catatan :");

        pembayaran_box.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        pembayaran_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Metode Pembayaran :");

        jPanel1.setBackground(new java.awt.Color(227, 242, 253));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Daftar Pesanan :");

        btn_hapus_item.setBackground(new java.awt.Color(255, 204, 204));
        btn_hapus_item.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus_item.setForeground(new java.awt.Color(255, 0, 0));
        btn_hapus_item.setText("Hapus Item Terpilih");
        btn_hapus_item.setBorderPainted(false);
        btn_hapus_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_itemActionPerformed(evt);
            }
        });

        list_keranjang.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(list_keranjang);

        cetakStruck.setBackground(new java.awt.Color(0, 51, 102));
        cetakStruck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cetakStruck.setForeground(new java.awt.Color(255, 255, 255));
        cetakStruck.setText("Cetak Struck");
        cetakStruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakStruckActionPerformed(evt);
            }
        });

        label_grand_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_grand_total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_grand_total.setText("GRAND TOTAL : Rp 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(btn_hapus_item, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cetakStruck, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_grand_total, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_hapus_item)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_grand_total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cetakStruck, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("Sudut Temu Ruang Rasa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nama_field, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(no_meja_field)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catatan_field))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(pembayaran_box, 0, 157, Short.MAX_VALUE))
                                    .addComponent(dropdown_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel11))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(harga))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pesan_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel12)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no_meja_field, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama_field, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(catatan_field, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dropdown_kategori)
                    .addComponent(harga)
                    .addComponent(total_harga)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pembayaran_box, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_meja_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_meja_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_meja_fieldActionPerformed

    private void nama_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_fieldActionPerformed

    private void dropdown_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kategoriActionPerformed
        if (dropdown_kategori.getSelectedItem() == null) {
        return;
        }
        String kategori = dropdown_kategori.getSelectedItem().toString();
        String[] data = null;

        if (kategori.equals("Makanan")) {
            data = new String[]
            {"Nashville Hot Chicken(Nasi)","Chicken Nanban Bowl","Cheesy Melt Chicken","Garlic Butter Chicken","Chicken Mushroom Steak","BBQ Glazed Wings",
             "The Trenggalek Smash Beef","Beef Black Pepper Bowl","Teriyaki Beef Sensation","Creamy Beef Pasta",
             "Cumi Crispy Platter","Golden Salted Egg Tuna","Seafood Marenara","Salmon Marenara",
             "Nasi Goreng Chicken Crispy","Nasi Goreng Smoked Beef & Cheese","Nasi Goreng Beef Blackpepper","Nasi Goreng Sausage Bratwurst","Nasi Goreng Garlic Prawn", };
            
            } 
        else if (kategori.equals("Minuman")) {
            data = new String[]
            {"Original Coffe","Aren Coffee Milk","Butterscotch Latte","Vanilla Cold Brew","Caramel Macchiato","Hazelnut Choco-Coffee",
             "Signature Matcha Latte","Matcha Berry Cream","Matcha Cookies Frappe","Milk matcha","Pure Matcha","Dark Choco Signature",
             "Lychee Spring Tea","Thai Tea Heritage","Strawberry Sparkle","original Tea","Lotus Biscoff Shake","Taro Velvet Latte",};
            } 
        else if (kategori.equals("Snack")) {
            data = new String[]
            {"Kentang Sultan Truffle","Kentang Bakar Mentai","Kulit Ayam Krenyes","Golden Onion Rings","Chicken Popcorn BBQ",
             "Potato Wedges Herbs","Banana Fritters Caramel","Platter Sharing","Roti Bakar","Cheesy Mozza Sticks"};
            }

        list_menu.setListData(data);
    }//GEN-LAST:event_dropdown_kategoriActionPerformed

    private void pesan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan_buttonActionPerformed
       String menu = list_menu.getSelectedValue();
       String porsi = jumlah.getValue().toString();
       String total = total_harga.getText();

       if (menu == null || total.isEmpty() || total.equals("0")) {
            JOptionPane.showMessageDialog(this, "Pilih menu dan jumlah dulu ya!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

    // Tambahkan ke daftar list
        String itemPesanan = menu + " (" + porsi + " porsi) - Rp " + total;
        modelDaftarPesanan.addElement(itemPesanan);

    // Update Grand Total
        grandTotal += Integer.parseInt(total);
        label_grand_total.setText("GRAND TOTAL: Rp " + grandTotal);
    
    // Optional: Reset input setelah tambah agar bisa pilih menu lain
        list_menu.clearSelection();
        jumlah.setValue(1);
        total_harga.setText("");
    }//GEN-LAST:event_pesan_buttonActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        no_meja_field.setText("");
        nama_field.setText("");
        catatan_field.setText(""); // Kosongkan catatan
        dropdown_kategori.setSelectedIndex(0);
        pembayaran_box.setSelectedIndex(0); // Reset pembayaran ke 'Tunai'
        list_menu.clearSelection();
        harga.setText("");
        jumlah.setValue(0);
        total_harga.setText("");
        no_meja_field.requestFocus();
        list_keranjang.setListData(new String[0]);
        label_grand_total.setText("GRAND TOTAL: Rp 0");
    }//GEN-LAST:event_resetActionPerformed

    private void list_menuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_menuValueChanged
        if (!evt.getValueIsAdjusting() && list_menu.getSelectedValue() != null) {
        String menuPilihan = list_menu.getSelectedValue();
        int hargaSatuan = 0;
        
        // Cek menu apa yang dipilih dan tentukan harganya
        switch (menuPilihan) {
            case "Nashville Hot Chicken(Nasi)": hargaSatuan = 25000; break;
            case "Chicken Nanban Bowl": hargaSatuan = 28000; break;
            case "Cheesy Melt Chicken": hargaSatuan = 27000; break;
            case "Garlic Butter Chicken": hargaSatuan = 26000; break;
            case "Chicken Mushroom Steak": hargaSatuan = 32000; break;
            case "BBQ Glazed Wings": hargaSatuan = 30000; break;
            case "The Trenggalek Smash Beef": hargaSatuan = 35000; break;
            case "Beef Black Pepper Bowl": hargaSatuan = 33000; break;
            case "Teriyaki Beef Sensation": hargaSatuan = 33000; break;
            case "Creamy Beef Pasta": hargaSatuan = 30000; break;
            case "Cumi Crispy Platter": hargaSatuan = 45000; break;
            case "Golden Salted Egg Tuna": hargaSatuan = 58000; break;
            case "Seafood Marenara": hargaSatuan = 150000; break;
            case "Salmon Marenara": hargaSatuan = 115000; break;
            case "Nasi Goreng Chicken Crispy": hargaSatuan = 28000; break;
            case "Nasi Goreng Smoked Beef & Cheese": hargaSatuan = 32000; break;
            case "Nasi Goreng Beef Blackpepper": hargaSatuan = 38000; break;
            case "Nasi Goreng Sausage Bratwurst": hargaSatuan = 25000; break;
            case "Nasi Goreng Garlic Prawn": hargaSatuan = 35000; break;
            
            case "Original Coffe": hargaSatuan = 10000; break;
            case "Aren Coffee Milk": hargaSatuan = 15000; break;
            case "Butterscotch Latte": hargaSatuan = 22000; break;
            case "Vanilla Cold Brew": hargaSatuan = 18000; break;
            case "Caramel Macchiato": hargaSatuan = 18000; break;
            case "Hazelnut Choco-Coffee": hargaSatuan = 23000; break;
            case "Signature Matcha Latte": hargaSatuan = 20000; break;
            case "Matcha Berry Cream": hargaSatuan = 20000; break;
            case "Matcha Cookies Frappe": hargaSatuan = 20000; break;
            case "Milk matcha": hargaSatuan = 15000; break;
            case "Pure Matcha": hargaSatuan = 20000; break;
            case "Dark Choco Signature": hargaSatuan = 15000; break;
            case "Lychee Spring Tea": hargaSatuan = 20000; break;
            case "Thai Tea Heritage": hargaSatuan = 20000; break;
            case "Strawberry Sparkle": hargaSatuan = 15000; break;
            case "original Tea": hargaSatuan = 20000; break;
            case "Lotus Biscoff Shake": hargaSatuan = 20000; break;
            case "Taro Velvet Latte": hargaSatuan = 28000; break;
            
            case "Kentang Sultan Truffle": hargaSatuan = 18000; break;
            case "Kentang Bakar Mentai": hargaSatuan = 22000; break;
            case "Kulit Ayam Krenyes": hargaSatuan = 15000; break;
            case "Golden Onion Rings": hargaSatuan = 15000; break;
            case "Chicken Popcorn BBQ": hargaSatuan = 20000; break;
            case "Potato Wedges Herbs": hargaSatuan = 17000; break;
            case "Banana Fritters Caramel": hargaSatuan = 16000; break;
            case "Platter Sharing": hargaSatuan = 35000; break;
            case "Roti Bakar": hargaSatuan = 15000; break;
            case "Cheesy Mozza Sticks": hargaSatuan = 25000; break;
               
        }
        
        // Tampilkan ke textfield 'harga'
        harga.setText(String.valueOf(hargaSatuan));
        hitungTotal(); // Panggil method hitung total setiap kali menu berubah
        }
    }//GEN-LAST:event_list_menuValueChanged

    private void jumlahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jumlahStateChanged
        hitungTotal();
    }//GEN-LAST:event_jumlahStateChanged

    private void cetakStruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakStruckActionPerformed
        if (modelDaftarPesanan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Belum ada pesanan di daftar!");
            return;
        }

        StringBuilder struk = new StringBuilder("=== STRUK PESANAN ===\n");
        struk.append("Nama: ").append(nama_field.getText()).append("\n");
        struk.append("----------------------------\n");

        for (int i = 0; i < modelDaftarPesanan.getSize(); i++) {
            struk.append(modelDaftarPesanan.getElementAt(i)).append("\n");
        }

        struk.append("----------------------------\n");
        struk.append("Catatan: ").append(catatan_field.getText()).append("\n");
        struk.append("TOTAL BAYAR: Rp ").append(grandTotal);
        

        JOptionPane.showMessageDialog(this, struk.toString(), "Pesanan Berhasil", JOptionPane.INFORMATION_MESSAGE);
    
    // Reset semuanya setelah cetak
        modelDaftarPesanan.clear();
        grandTotal = 0;
        label_grand_total.setText("GRAND TOTAL: Rp 0");
        
        no_meja_field.setText("");      
        nama_field.setText("");         
        catatan_field.setText("");
        harga.setText("");
        jumlah.setValue(0);
        dropdown_kategori.setSelectedIndex(0);
        pembayaran_box.setSelectedIndex(0);
    }//GEN-LAST:event_cetakStruckActionPerformed

    private void btn_hapus_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_itemActionPerformed
        int selectedIndex = list_keranjang.getSelectedIndex();

    // Pastikan user benar-benar memilih item (index tidak -1)
    if (selectedIndex != -1) {
        // Ambil teks dari item yang dipilih
        String itemText = modelDaftarPesanan.getElementAt(selectedIndex);

        try {
            // Karena format text Anda sebelumnya: "Menu (x porsi) - Rp 50000"
            // Kita pisahkan (split) string-nya berdasarkan "- Rp " untuk mengambil angkanya saja
            String[] parts = itemText.split("- Rp ");
            
            if (parts.length == 2) {
                // Konversi string harga yang didapat kembali menjadi angka integer
                int hargaItem = Integer.parseInt(parts[1].trim());
                
                // Kurangi grandTotal saat ini dengan harga item yang dihapus
                grandTotal -= hargaItem; 
            }
        } catch (Exception e) {
            System.out.println("Gagal mengekstrak harga dari list");
        }

        // 2. Hapus item tersebut dari list model keranjang
        modelDaftarPesanan.remove(selectedIndex);

        // 3. Jika keranjang kosong setelah dihapus, pastikan grand total jadi 0
        if (modelDaftarPesanan.isEmpty()) {
            grandTotal = 0;
        }

        // 4. Update tulisan di Label Grand Total
        label_grand_total.setText("GRAND TOTAL: Rp " + grandTotal);

    } else {
        // Tampilkan peringatan jika user klik hapus tapi belum memilih item di list
        JOptionPane.showMessageDialog(this, "Pilih pesanan yang ingin dihapus terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btn_hapus_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pertemuan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pertemuan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pertemuan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pertemuan6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pertemuan6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus_item;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField catatan_field;
    private javax.swing.JButton cetakStruck;
    private javax.swing.JComboBox<String> dropdown_kategori;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jumlah;
    private javax.swing.JLabel label_grand_total;
    private javax.swing.JList<String> list_keranjang;
    private javax.swing.JList<String> list_menu;
    private javax.swing.JTextField nama_field;
    private javax.swing.JTextField no_meja_field;
    private javax.swing.JComboBox<String> pembayaran_box;
    private javax.swing.JButton pesan_button;
    private javax.swing.JButton reset;
    private javax.swing.JTextField total_harga;
    // End of variables declaration//GEN-END:variables
}
